main: net.warvale.prison.Prison
name: Locked
version: 1.0
author: The Warvale Developers
description: Warvale Prison Core
commands:
  scrap:
    description: Manage the eco
    usage: /scrap <set/get> <player> [amount (only if its set)]
  givesubstance:
    description: Give a specified player or yourself a specified substance.
    usage: /givedrug <substance> [player]
    permission: locked.give
    aliases: [gd]
  resetores:
    description: Reset all of the ores in the mine.
    permisson: locked.resetores
    aliases: [resetmine]
  givegoditem:
    description: Gives yourself a God item
    permission: locked.give
  setstatus:
    description: Set the status of any player (prisoner, guard, warden)
    permission: locked.admin
  msg:
    description: Send a player a private message.
  r:
    description: Send a message to the last player you messaged or recieved a message from.
  pay:
    description: Pay another player a specified amount of vales.
  who:
    description: Show all online players.
  shopnpc:
    description: Every command involving a shop npc.
    permission: locked.admin
  npc:
    description: Reset npcs.
    permission: locked.admin
permissions: {}