main: net.warvale.prison.Prison
name: Locked
version: 1.0
author: The Warvale Developers
description: Warvale Prison Core
commands:
  vale:
    description: Manage the eco
    usage: /vale <set/get> <player> [amount (only if its set)]
  givesubstance:
    description: Give a specified player or yourself a specified substance.
    usage: /givedrug <substance> [player]
    permission: locked.give
    aliases: [gd]
  resetores:
    description: Reset all of the ores in the mine.
    permisson: locked.resetores
    aliases: [resetmine]
  givegoditem:
    description: Gives yourself a God item
    permission: locked.give
  setstatus:
    description: Set the status of any player (prisoner, guard, warden)
    permission: locked.admin
permissions: {}